build_from:
  arm64: "debian:stable-slim"
labels:
  org.opencontainers.image.title: "V1T0: Addons"
  org.opencontainers.image.description: "Utilita'"
  org.opencontainers.image.source: "https://github.com/vfoschi/addons-ha"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
